DROP TABLE `acoesUsuario`;--> statement-breakpoint
DROP TABLE `aprendizados`;--> statement-breakpoint
DROP TABLE `arquivosMissao`;--> statement-breakpoint
DROP TABLE `configuracaoIA`;--> statement-breakpoint
DROP TABLE `conversasWhatsapp`;--> statement-breakpoint
DROP TABLE `documentosGerados`;--> statement-breakpoint
DROP TABLE `documentosWhatsapp`;--> statement-breakpoint
DROP TABLE `eventos`;--> statement-breakpoint
DROP TABLE `linksCobranca`;--> statement-breakpoint
DROP TABLE `membrosEquipe`;--> statement-breakpoint
DROP TABLE `mensagensWhatsapp`;--> statement-breakpoint
DROP TABLE `missoes`;--> statement-breakpoint
DROP TABLE `modelos`;--> statement-breakpoint
DROP TABLE `multas`;--> statement-breakpoint
DROP TABLE `notificacoes`;--> statement-breakpoint
DROP TABLE `padroesAprendidos`;--> statement-breakpoint
DROP TABLE `registros`;--> statement-breakpoint
DROP TABLE `relatorios`;--> statement-breakpoint
DROP TABLE `servicos`;--> statement-breakpoint
DROP TABLE `tarefas`;--> statement-breakpoint
DROP TABLE `templatesWhatsapp`;